# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true
  issues:
    exclude-files:
      - \.pb\.go$
      - \.pb\.gw\.go$
    exclude-dirs:
      - bin
      - vendor
      - var
      - tmp
      - .cache

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    shadow: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - typecheck
    - unused

issues:
  exclude-use-default: false
  exclude:
    - G104 # _ instead of err checks
    - exported func .* returns unexported type .*, which can be annoying to use
    - should have a package comment
    - don't use an underscore in package name
    - type UserApi should be UserAPI
    - struct field userApi should be userAPI
    - type name will be used as user.UserApi by other packages, and that stutters; consider calling this Api
    - parameter 'ctx' seems to be unused, consider removing or renaming it as _
    - struct{name string; args struct{ctx context.Context; id int64}; want google.golang.org/protobuf/types/known/emptypb.Empty; err error; userRepository github.com/ArturSaga/auth/internal/service/user/tests.userRepositoryMockFunc; redisClient github.com/ArturSaga/auth/internal/service/user/tests.redisClientMockFunc; txManager github.com/ArturSaga/auth/internal/service/user/tests.transactionMockFunc} contains google.golang.org/protobuf/types/known/emptypb.Empty contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex
    - struct{name string; args struct{ctx context.Context; updateUserInfo *github.com/ArturSaga/auth/internal/model.UpdateUserInfo}; want google.golang.org/protobuf/types/known/emptypb.Empty; err error; userRepository github.com/ArturSaga/auth/internal/service/user/tests.userRepositoryMockFunc; redisClient github.com/ArturSaga/auth/internal/service/user/tests.redisClientMockFunc; txManager github.com/ArturSaga/auth/internal/service/user/tests.transactionMockFunc} contains google.golang.org/protobuf/types/known/emptypb.Empty contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex
    - google.golang.org/protobuf/types/known/emptypb.Empty contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex
